### ISSUE TITLE
redirect HTTP requests to HTTPS equivalent

### ISSUE THREAD

**Issue by mykmelez** [mykmelez/wordpress-pwa#1]
Since the push plugin needs WordPress to be served via HTTPS, the image should include a .htaccess file that forces Apache to redirect any HTTP requests to their HTTPS equivalent.

**Comment by marco-c** [comment]
Isn't this fixed now with edced4e9c9992e446b37ae4c48b97626c54e0cae?

**Comment by mykmelez** [comment]
> Isn't this fixed now with edced4e?

Effectively, yes. If you enable the plugin installed by that change, it'll ensure that HTTP requests are redirected to HTTPS. That requires you to enable the plugin, but I'm ok with that. In fact I think it's better that way, because you probably don't want to enable the plugin when using the image for development. (Theoretically, this plugin is not as secure as an Apache rule that forces requests to HTTPS, but it's good enough.)
