### ISSUE TITLE
Support newer versions of the Web Push plugin that contain a build step

### ISSUE THREAD

**Issue by marco-c** [mykmelez/wordpress-pwa#2]
https://github.com/mozilla/wp-web-push/issues/132

@mykmelez you could either run the build step and then install the plugin, or download the plugin from WordPress.org. The first solution would probably be better (so that we can easily test pre-release versions).

**Comment by mykmelez** [comment]
> @mykmelez you could either run the build step and then install the plugin, or download the plugin from WordPress.org. The first solution would probably be better (so that we can easily test pre-release versions).

Yes, better to build the plugin, so we can test pre-release versions. https://github.com/mykmelez/wordpress-pwa/commit/6c4b6ef740a98d7c175296def63d205beb9c8e5a does that.
