### ISSUE TITLE
Update submodule URLs

### ISSUE THREAD

**Issue by marco-c** [mykmelez/wordpress-pwa#8]
https://github.com/marco-c/wp-web-push -> https://github.com/mozilla/wp-web-push
https://github.com/darkwing/wp-sw-cache -> https://github.com/mozilla/wp-offline-shell

**Comment by mykmelez** [comment]
I've updated offline-shell in https://github.com/mykmelez/wordpress-pwa/commit/40950a63e8ffae86c7574449ba13770952b0e14c and https://github.com/mykmelez/wordpress-pwa/commit/9e18f86d34879b07cb4daef68ebec4485d735b0b.

I've updated wp-web-push in https://github.com/mykmelez/wordpress-pwa/pull/10/commits/15bfc08e8cc137a97f26d12ae54214fb3e8e65d0, which is pending in https://github.com/mykmelez/wordpress-pwa/pull/10.

**Comment by mykmelez** [comment]
Since #10 is taking its time, I updated wp-web-push separately in https://github.com/mykmelez/wordpress-pwa/commit/e363f75b42d81eb86ff8ba90474e0b222c22cf2a.
